version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "photo-app-rest-api-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cn7fzpkggpu3"
s3_prefix = "photo-app-rest-api-sam"
region = "eu-west-1"
profile = "admin-development"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
